language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
sudo: required
env:
  global:
    - PACKAGE="mirage-os-shim"
    - PINS="depext:0.9.1 mirage-unix:git://github.com/mirage/mirage-platform.git mirage-xen:git://github.com/mirage/mirage-platform.git"
    - DEPOPTS=mirage-xen
  matrix:
    - OCAML_VERSION=4.01
    - OCAML_VERSION=4.02
    - OCAML_VERSION=4.03
notifications:
  email: false

# XXX FIXME: test with solo5

